version: '3.7'
services:

  web: 
    build: ./application
    volumes:
      - ./application/project/static:/app/project/static
      - ./application/project/templates:/app/project/templates
      - ./application/log:/app/log
    depends_on:
      - postgres
    expose:
      - 5000
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      crud:

  postgres:
    image: postgres:12.0-alpine
    environment:
      TZ: 'Europe/Budapest'
      PGTZ: 'Europe/Budapest'
    volumes:
        - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      crud:

  nginx:
    build: ./nginx
    volumes:
      - ./application/project/static:/app/project/static
    ports:
      - 1335:80
      # - 1335:443
    depends_on:
      - web
    restart: unless-stopped
    networks:
      crud:


networks:
  crud:

volumes:
  postgres:
  static:
  logs:
